language: ruby
rvm:
  - "2.5.0"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - rails db:create
bundler_args: --binstubs=./bundler_stubs
